/*
 * This file is generated by jOOQ.
 */
package com.onedata.jooq.pokemon.db;


import com.onedata.jooq.pokemon.db.tables.Pokemon;
import com.onedata.jooq.pokemon.db.tables.records.PokemonRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PokemonRecord> POKEMON_PKEY = Internal.createUniqueKey(Pokemon.POKEMON, DSL.name("pokemon_pkey"), new TableField[]{Pokemon.POKEMON.ID}, true);
}
