/*
 * This file is generated by jOOQ.
 */
package com.onedata.jooq.pokemon.db;


import com.onedata.jooq.pokemon.db.tables.Pokemon;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.pokemon</code>.
     */
    public static final Pokemon POKEMON = Pokemon.POKEMON;
}
