/*
 * This file is generated by jOOQ.
 */
package com.onedata.jooq.pokemon.db.tables.records;


import com.onedata.jooq.pokemon.db.tables.Pokemon;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PokemonRecord extends UpdatableRecordImpl<PokemonRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached PokemonRecord
     */
    public PokemonRecord() {
        super(Pokemon.POKEMON);
    }

    /**
     * Create a detached, initialised PokemonRecord
     */
    public PokemonRecord(Integer id, String name, String type, Integer hp) {
        super(Pokemon.POKEMON);

        setId(id);
        setName(name);
        setType(type);
        setHp(hp);
    }

    /**
     * Create a detached, initialised PokemonRecord
     */
    public PokemonRecord(com.onedata.jooq.pokemon.db.tables.pojos.Pokemon value) {
        super(Pokemon.POKEMON);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setType(value.getType());
            setHp(value.getHp());
        }
    }

    /**
     * Getter for <code>public.pokemon.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.pokemon.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pokemon.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pokemon.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pokemon.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>public.pokemon.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>public.pokemon.hp</code>.
     */
    public Integer getHp() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.pokemon.hp</code>.
     */
    public void setHp(Integer value) {
        set(3, value);
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Pokemon.POKEMON.ID;
    }

    @Override
    public Field<String> field2() {
        return Pokemon.POKEMON.NAME;
    }

    @Override
    public Field<String> field3() {
        return Pokemon.POKEMON.TYPE;
    }

    @Override
    public Field<Integer> field4() {
        return Pokemon.POKEMON.HP;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public Integer component4() {
        return getHp();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public Integer value4() {
        return getHp();
    }

    @Override
    public PokemonRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PokemonRecord value2(String value) {
        setName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public PokemonRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public PokemonRecord value4(Integer value) {
        setHp(value);
        return this;
    }

    @Override
    public PokemonRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
